{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.programs.fish;

  fishAbbrs = lib.concatStringsSep "\n" (
    lib.mapAttrsToList
      (name: value: "abbr -a ${name} -- ${lib.escapeShellArg value}")
      cfg.shellAbbrs
  );

  fishAliases = lib.concatStringsSep "\n" (
    lib.mapAttrsToList
      (name: value: "alias ${name} ${lib.escapeShellArg value}")
      (lib.filterAttrs (_: value: value != null) cfg.shellAliases)
  );
in
{
  options.programs.fish = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable [fish](${pkgs.fish.meta.homepage}).
      '';
    };

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.fish;
      defaultText = lib.literalExpression "pkgs.fish";
      description = ''
        The package to use for `fish`.
      '';
    };

	shellAbbrs = lib.mkOption {
        default = { };
        example = {
          gco = "git checkout";
          npu = "nix-prefetch-url";
        };
        description = ''
          Set of fish abbreviations.
        '';
        type = with lib.types; attrsOf str;
      };

      shellAliases = lib.mkOption {
        default = { };
        description = ''
          Set of aliases for fish shell, which overrides {option}`environment.shellAliases`.
          See {option}`environment.shellAliases` for an option format description.
        '';
        type = with lib.types; attrsOf (nullOr (either str path));
      };

      shellInit = lib.mkOption {
        default = "";
        description = ''
          Shell script code called during fish shell initialisation.
        '';
        type = lib.types.lines;
      };
  };

  config = lib.mkIf cfg.enable {
    environment = {
      pathsToLink = [ "/share/fish" ];
      systemPackages = [ cfg.package ];
      shells = [
        "/run/current-system/sw/bin/fish"
        (lib.getExe cfg.package)
      ];
	  
	  etc."fish/config.fish".text = ''
      	# Generated by Finix :)

      	${fishAbbrs}

      	${fishAliases}

      	${cfg.shellInit}
      '';
    };
  };
}
