{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.programs.doas;
in
{
  imports = [
    ./providers.privileges.nix
  ];

  options.programs.doas = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable [doas](${pkgs.doas.meta.homepage}).
      '';
    };

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.doas;
      defaultText = lib.literalExpression "pkgs.doas";
      description = ''
        The package to use for `doas`.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [
      cfg.package
    ];

    security.pam.services.doas.text = ''
      # Account management.
      account required pam_unix.so # unix (order 10900)

      # Authentication management.
      auth sufficient pam_unix.so likeauth nullok try_first_pass # unix (order 11600)
      auth required pam_deny.so # deny (order 12400)

      # Password management.
      password sufficient pam_unix.so nullok yescrypt # unix (order 10200)

      # Session management.
      session required pam_env.so conffile=/etc/security/pam_env.conf readenv=0 # env (order 10100)
      session required pam_unix.so # unix (order 10200)
    '';

    environment.etc."doas.conf" = {
      mode = "0440";
      text = lib.mkMerge [
        (lib.mkBefore ''
          # do not edit this file
        '')

        (lib.mkAfter ''
          # "root" is allowed to do anything.
          permit nopass keepenv root

          # access for members of the "wheel" group
          permit setenv { SSH_AUTH_SOCK TERMINFO TERMINFO_DIRS } :wheel
        '')
      ];

      source =
        let
          value =
            pkgs.runCommand "doas.conf.in"
              {
                src = pkgs.writeText "doas.conf.in" config.environment.etc."doas.conf".text;
                preferLocalBuild = true;
              }
              # Make sure that the doas.conf file is syntactically valid.
              "${pkgs.buildPackages.doas}/bin/doas -C $src && cp $src $out";
        in
        lib.mkForce value;
    };

    security.wrappers.doas = {
      setuid = true;
      owner = "root";
      group = "root";
      source = lib.getExe cfg.package;
    };

    # this module supplies an implementation for `providers.privileges`
    providers.privileges.backend = "doas";
  };
}
