{
  modules,
  config,
  pkgs,
  lib,
  ...
}:
{
  imports = [
    ./graphics
    ./networking
    ./amd-cpu.nix
    ./bluetooth.nix
    ./disk.nix
    ./firmware.nix
    ./keyboard.nix
    ./virtualisation.nix
    # ./debug.nix FIXME: requires nixpkgs.hostPlatform or something similar
  ];

  options.hardware.facter = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = config.hardware.facter.report != { };
      defaultText = lib.literalExpression ''
        config.hardware.facter.report != { }
      '';
      description = ''
        Whether to enable automatic hardware configuration using a report generated by nixos-facter.

        See <https://nix-community.github.io/nixos-facter/> for more information.
      '';
    };

    report = lib.mkOption {
      type = lib.types.attrsOf lib.types.anything;
      default =
        if config.hardware.facter.reportPath == null then
          { }
        else
          builtins.fromJSON (builtins.readFile config.hardware.facter.reportPath);
      defaultText = "A JSON import from config.hardware.facter.reportPath (if not null), {} otherwise.";
      description = ''
        Hardware report data generated by nixos-facter.

        See <https://nix-community.github.io/nixos-facter/> for more information.
      '';
    };

    reportPath = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = ''
        Path to a hardware report generated by nixos-facter.

        To generate a report, run the following as root:
        ```
        nix-shell -p nixos-facter --run nixos-facter > facter.json
        ```

        See <https://nix-community.github.io/nixos-facter/> for more information.
      '';
    };
  };
}
